#!/bin/bash
jupyter labextension install --no-build @jupyter-widgets/jupyterlab-manager
jupyter lab build
jupyter lab clean
cd /home/jovyan pip install .
python -c "help('modules')"
python /home/jovyan/share/scripts/make_glm_files.py
