#!/bin/bash
jupyter labextension install --no-build @jupyter-widgets/jupyterlab-manager
jupyter lab build
jupyter lab clean
python /home/jovyan/setup.py develop
python -m /home/jovyan/share/scripts/make_glm_files.py
